name: Docker image build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DOCKER_FILE: "./Dockerfile"
  DOCKER_REGISTRY: "gcr.io/diesel-media-340214"
  DOCKER_BUILDKIT: 1
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Get Short SHA  
    
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha12::$(echo ${GITHUB_SHA} | cut -c1-12)"

   # Get branch name 

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]"$(echo "${GITHUB_REF#refs/heads/}" | sed 's/\//_/g')
      id: extract_branch

    # Gcr login

    - name: Login to Google Container Registry
      uses: docker/login-action@v1
      with:
        registry: https://gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}
        
    # Insatll java jdk
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    #Grant permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Build and test using gradlew
    - name: Build and test services
      run: |
        ./gradlew clean
        ./gradlew build        

    # Package images 
    - name: Package Image
      if: github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main' || github.ref == 'refs/heads/staging' || github.event.pull_request.base.ref == 'staging' || github.ref == 'refs/heads/dev' || github.event.pull_request.base.ref == 'dev'
      run: |
        docker build . \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from ${DOCKER_REGISTRY}/${{ github.event.repository.name }}:${{ steps.extract_branch.outputs.branch }} \
          -f ${DOCKER_FILE} \
          -t ${DOCKER_REGISTRY}/${{ github.event.repository.name }}:${{ steps.extract_branch.outputs.branch }} \
          -t ${DOCKER_REGISTRY}/${{ github.event.repository.name }}:${{ steps.extract_branch.outputs.branch }}_${{ steps.slug.outputs.sha12 }} \
          -t ${DOCKER_REGISTRY}/${{ github.event.repository.name }}:${{ steps.slug.outputs.sha12 }}

    # Push docker images to gcr 
    - name: Push images to gcr
      if: github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main' || github.ref == 'refs/heads/staging' || github.event.pull_request.base.ref == 'staging' || github.ref == 'refs/heads/dev' || github.event.pull_request.base.ref == 'dev'
      run: |
        docker push ${DOCKER_REGISTRY}/${{ github.event.repository.name }}:${{ steps.extract_branch.outputs.branch }}
        docker push ${DOCKER_REGISTRY}/${{ github.event.repository.name }}:${{ steps.extract_branch.outputs.branch }}_${{ steps.slug.outputs.sha12 }}
        docker push ${DOCKER_REGISTRY}/${{ github.event.repository.name }}:${{ steps.slug.outputs.sha12 }}

